services:
  srs:
    image: ossrs/srs:5       # Use the official SRS Docker image
    container_name: srs
    ports:
      - "1935:1935"          # RTMP & WebRTC signaling
      - "1985:1985"          # HTTP API and statistics
      - "8080:8080"          # HLS/LL-HLS
      - "10080:10080/udp"    # WebRTC media transport (UDP)
    volumes:
      - ./config/srs.conf:/usr/local/srs/conf/srs.conf  # Map custom SRS config
    command: ["./objs/srs", "-c", "conf/srs.conf"]      # Start SRS with your config